In [1]:
import scipy.stats as stats

In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset = sns.load_dataset('tips')

In [3]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
dataset_table = pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [5]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [6]:
#Observed Values
observed_values = dataset_table.values
print("Observed Values:\n",observed_values)

Observed Values:
 [[60 97]
 [33 54]]


In [7]:
val = stats.chi2_contingency(dataset_table)

In [8]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [9]:
val[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [10]:
Expected_values = val[3]

In [11]:
Expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [12]:
# Calculate degree of freedom
no_of_rows = len(dataset_table.iloc[0:2,0])
no_of_columns = len(dataset_table.iloc[0,0:2])
dof = (no_of_rows - 1) * (no_of_columns - 1)
print("Degree of Freedom:",dof)
alpha = 0.05

Degree of Freedom: 1


In [13]:
#Calculate Chi-square test
def cal_chisquare(Observed_values,Expected_values):
    observ_list = []
    expect_list = []
    sum = 0
    for i in Observed_values:
        for j in i:
            observ_list.append(j)
            
    for i in Expected_values:
        for j in i:
            expect_list.append(j)
            
    for i in range(len(observ_list)):
        sum = sum + (((observ_list[i] - expect_list[i])**2)/expect_list[i])
        
    return sum

In [17]:
chi_square_statistics = cal_chisquare(observed_values,Expected_values)
print("Chi-square statistics:-",chi_square_statistics)

Chi-square statistics:- 0.001934818536627623


In [15]:
# Decision Rule(Getting value from chi-square table)
from scipy.stats import chi2

critical_value = chi2.ppf(q=1-alpha,df=dof)
print("Critical Value=",critical_value)

Critical Value= 3.841458820694124


In [21]:
#p-value
p_value = 1 - chi2.cdf(x=chi_square_statistics,df=dof)
print("p-value:",p_value)
print("Significance level:",alpha)
print("Degree of freedom",dof)

p-value: 0.964915107315732
Significance level: 0.05
Degree of freedom 1


In [22]:
#Conclusion
if chi_square_statistics >= critical_value:
    print("Reject Null Hypothesis(H0)")
    print("Accepet Alternate Hypothesis(H1)")
    print("There is a relationship between 2 categorical variable")
else:
    print("Accept Null Hypothesis(H0)")
    print("Reject Alternate Hepothesis(H1)")
    print("There is no relationship between 2 categorical variable")
    

if p_value <= alpha:
    print("Reject Null Hypothesis(H0)")
    print("Accepet Alternate Hypothesis(H1)")
    print("There is a relationship between 2 categorical variable")
else:
    print("Accept Null Hypothesis(H0)")
    print("Reject Alternate Hepothesis(H1)")
    print("There is no relationship between 2 categorical variable")

Accept Null Hypothesis(H0)
Reject Alternate Hepothesis(H1)
There is no relationship between 2 categorical variable
Accept Null Hypothesis(H0)
Reject Alternate Hepothesis(H1)
There is no relationship between 2 categorical variable


In [4]:
import pandas as pd
import scipy.stats as stats

In [2]:
df = pd.read_csv('medication.csv')

In [3]:
df

0 mg  50 mg  100 mg
0     9      7       4
1     8      6       3
2     7      6       2
3     8      7       3
4     8      8       4
5     9      7       3
6     8      6       2

In [5]:
F, p = stats.f_oneway(df['0 mg'], df['50 mg'], df['100 mg'])

In [6]:
print(p)

5.956341358737431e-10


In [8]:
if p<0.05:
    print("Reject Null Hypothesis(H0)")
else:
    print("Accept Null Hypothesis(H0)")
    

Reject Null Hypothesis(H0)


#### Z Test Example

In [2]:
from statsmodels.stats.weightstats import ztest as ztest

data = [88,92,94,94,96,97,97,97,99,99,105,109,109,109,110,112,112,113,114,115]
_,p_value = ztest(data,value=110)

In [4]:
p_value

0.00027212221833431376

In [3]:
if p_value<0.05:
    print("Reject Null hypothesis(H0)")
else:
    print("Accept Null hypothesis(H0)")

Reject Null hypothesis(H0)
